- name: Update and upgrade dns servers
  apt: 
      update_cache: yes
      upgrade: dist

    - name: Install bind9
      apt:
          name:
            - bind9
            - dnsutils
            - bind9utils
          state: latest

- name: Start and enable bind9
  tags: bind,dns
  service:
      name: bind9
      state: started
      enabled: yes
  when: ansible_distribution == "CentOS"

- name: Create /var/named/zones directory
  file:
      path: /var/named/zones
      state: directory
      owner: root
      group: root
      mode: 0755

- name: Copy bind9 configuration files for primary DNS server
  tags: bind,dns
  copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      group: "{{ item.group }}"
      owner: root
      mode: 0644
  with_items:
      - { src: 'files/bind9', dest: '/etc/default/bind9', group: 'root' }
      - { src: 'files/named.conf.options', dest: '/etc/bind/named.conf.options', group: 'bind' }
      - { src: 'files/named.conf.local', dest: '/etc/bind/named.conf.local', group: 'bind' }
      - { src: 'files/db.dev.invalid', dest: '/var/named/zones/db.dev.invalid', group: 'bind' }
      - { src: 'files/db.192.168.12', dest: '/var/named/zones/db.192.168.12', group: 'bind' }
      
- name: Change serial number in zone file
  tags: bind,dns
  lineinfile:
      path: /var/named/zones/db.dev.invalid
      regexp: 'Serial'
      line:                               1         ; Serial
  when: ansible_distribution == "CentOS"
  notify: restart_bind
